import { Box, Button, Stack, Typography } from '@mui/material';

export function CardItem({ item, projectedState, disabled = false, onLockToggle, onRemove, onEditParticipant, onMove, linkMode, onLinkClick, onLinkTargetClick, conflictMode, onConflictClick, onConflictTargetClick, onPlayWithout }) {
  const label = item.type === 'hole' ? 'Trou' : projectedState.participants[item.participantId]?.name;
  const itemId = item.appearanceId ?? item.holeId;
  const isAnchor = linkMode?.anchor?.id === itemId;
  const isSelected = linkMode?.selectedTargets?.some((target) => target.id === itemId);
  const canSelect = linkMode && !isAnchor && linkMode.anchor.instrumentId !== item.instrumentId;
  const isConflictAnchor = conflictMode?.anchor?.id === itemId;
  const isConflictSelected = conflictMode?.selectedTargets?.some((target) => target.id === itemId);
  const canSelectConflict = conflictMode && item.type !== 'hole' && !isConflictAnchor;
  return <Box role="group" tabIndex={0} aria-label={`${label} ${item.isPlayed ? 'joué' : 'à jouer'}`} onClick={() => { if (canSelect) onLinkTargetClick(item); if (canSelectConflict) onConflictTargetClick(item); }} sx={{ border: '1px solid', borderColor: isConflictAnchor ? 'error.main' : isConflictSelected ? 'warning.main' : isAnchor ? 'primary.main' : isSelected ? 'secondary.main' : item.isLocked ? 'primary.main' : 'divider', borderRadius: 1.5, p: 1, minHeight: 96, outline: 'none', transition: 'background-color 180ms ease, border-color 180ms ease', '&:focus-visible': { boxShadow: 3, borderColor: 'primary.main' }, bgcolor: item.isPlayed ? 'action.disabledBackground' : canSelect || canSelectConflict ? 'action.hover' : 'background.paper' }}><Stack spacing={0.5}><Typography>{label}</Typography><Typography variant="caption" color="text.secondary">{item.isLinked ? 'lié · ' : ''}{item.isLocked ? 'verrouillé · ' : ''}{item.isPlayed ? 'joué · ' : ''}Round {item.appearanceIndex}</Typography><Stack direction="row" spacing={1} useFlexGap flexWrap="wrap"><Button size="small" aria-label={`Link ${label}`} sx={{ minHeight: 36 }} variant={isAnchor || item.isLinked ? 'contained' : 'outlined'} disabled={disabled} onClick={(event) => { event.stopPropagation(); onLinkClick(item); }}>{isAnchor ? 'Annuler link' : item.isLinked ? 'Unlink' : 'Link'}</Button><Button size="small" aria-label={`${item.isLocked ? 'Déverrouiller' : 'Verrouiller'} ${label}`} sx={{ minHeight: 36 }} disabled={disabled} onClick={() => onLockToggle(item)}>{item.isLocked ? 'Unlock' : 'Lock'}</Button>{item.type !== 'hole' ? <Button size="small" aria-label={`Modifier ${label}`} sx={{ minHeight: 36 }} disabled={disabled} onClick={() => onEditParticipant(item.participantId)}>Modifier</Button> : null}{item.type !== 'hole' ? <Button size="small" aria-label={`Conflit ${label}`} sx={{ minHeight: 36 }} color={isConflictAnchor || isConflictSelected ? 'error' : 'inherit'} disabled={disabled} onClick={(event) => { event.stopPropagation(); onConflictClick(item); }}>{isConflictAnchor ? 'Annuler conflit' : 'Conflit'}</Button> : null}{item.type !== 'hole' ? <Button size="small" aria-label={`Jouer sans ${label}`} sx={{ minHeight: 36 }} disabled={disabled} onClick={() => onPlayWithout(item)}>Jouer sans…</Button> : null}<Button size="small" aria-label={`Monter ${label}`} sx={{ minHeight: 36, minWidth: 44 }} disabled={disabled || item.isLocked || item.isPlayed} onClick={() => onMove(item, -1)}>↑</Button><Button size="small" aria-label={`Descendre ${label}`} sx={{ minHeight: 36, minWidth: 44 }} disabled={disabled || item.isLocked || item.isPlayed} onClick={() => onMove(item, 1)}>↓</Button><Button size="small" aria-label={`Supprimer ${label}`} sx={{ minHeight: 36 }} color="error" disabled={disabled} onClick={() => onRemove(item)}>Supprimer</Button></Stack></Stack></Box>;
}
