export const actionTypes = {
  CREATE_JAM: "CREATE_JAM",
  UPDATE_JAM: "UPDATE_JAM",
  ADD_INSTRUMENT: "ADD_INSTRUMENT",
  REORDER_INSTRUMENTS: "REORDER_INSTRUMENTS",

  ADD_PARTICIPANT: "ADD_PARTICIPANT",
  UPDATE_PARTICIPANT: "UPDATE_PARTICIPANT",
  MARK_PARTICIPANT_LEFT: "MARK_PARTICIPANT_LEFT",

  ADD_PARTICIPANT_ENTRY: "ADD_PARTICIPANT_ENTRY",
  UPDATE_PARTICIPANT_ENTRY: "UPDATE_PARTICIPANT_ENTRY",

  MOVE_ENTRY_VERTICAL: "MOVE_ENTRY_VERTICAL",

  LINK_ITEMS: "LINK_ITEMS",
  UNLINK_ITEMS: "UNLINK_ITEMS",

  ADD_HOLE: "ADD_HOLE",
  REMOVE_HOLE: "REMOVE_HOLE",
  WANTS_TO_PLAY_WITHOUT: "WANTS_TO_PLAY_WITHOUT",

  MARK_ENTRY_PLAYED: "MARK_ENTRY_PLAYED",
  MARK_PLATEAU_PLAYED: "MARK_PLATEAU_PLAYED",
  UNDO_ENTRY_PLAYED: "UNDO_ENTRY_PLAYED",
  UNDO_PLATEAU_PLAYED: "UNDO_PLATEAU_PLAYED",

  REPLACE_UNAVAILABLE: "REPLACE_UNAVAILABLE",
};
