export const actionTypes = {
  CREATE_JAM: "CREATE_JAM",
  UPDATE_JAM: "UPDATE_JAM",
  ADD_INSTRUMENT: "ADD_INSTRUMENT",
  REORDER_INSTRUMENTS: "REORDER_INSTRUMENTS",

  ADD_PARTICIPANT: "ADD_PARTICIPANT",
  UPDATE_PARTICIPANT: "UPDATE_PARTICIPANT",
  MARK_PARTICIPANT_LEFT: "MARK_PARTICIPANT_LEFT",

  ADD_PARTICIPANT_ENTRY: "ADD_PARTICIPANT_ENTRY",
  UPDATE_PARTICIPANT_ENTRY: "UPDATE_PARTICIPANT_ENTRY",

  MOVE_ENTRY_VERTICAL: "MOVE_ENTRY_VERTICAL",
  ENSURE_ROUND_SLOTS: "ENSURE_ROUND_SLOTS",
  MOVE_ROUND_SLOT_VERTICAL: "MOVE_ROUND_SLOT_VERTICAL",

  LINK_ITEMS: "LINK_ITEMS",
  UNLINK_ITEMS: "UNLINK_ITEMS",
  LINK_ROUND_SLOTS: "LINK_ROUND_SLOTS",
  UNLINK_ROUND_SLOTS: "UNLINK_ROUND_SLOTS",

  ADD_HOLE: "ADD_HOLE",
  REMOVE_HOLE: "REMOVE_HOLE",
  WANTS_TO_PLAY_WITHOUT: "WANTS_TO_PLAY_WITHOUT",
  ADD_ROUND_HOLE: "ADD_ROUND_HOLE",
  REMOVE_ROUND_HOLE: "REMOVE_ROUND_HOLE",
  WANTS_TO_PLAY_WITHOUT_ROUND: "WANTS_TO_PLAY_WITHOUT_ROUND",

  MARK_ENTRY_PLAYED: "MARK_ENTRY_PLAYED",
  MARK_ROUND_SLOT_PLAYED: "MARK_ROUND_SLOT_PLAYED",
  UNDO_ROUND_SLOT_PLAYED: "UNDO_ROUND_SLOT_PLAYED",
  MARK_PLATEAU_PLAYED: "MARK_PLATEAU_PLAYED",
  UNDO_ENTRY_PLAYED: "UNDO_ENTRY_PLAYED",
  UNDO_PLATEAU_PLAYED: "UNDO_PLATEAU_PLAYED",

  REPLACE_UNAVAILABLE: "REPLACE_UNAVAILABLE",
};
