# Generated manually for Confiture.live initial event-sourcing schema.
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Jam', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('jam_id', models.CharField(max_length=80, unique=True)),('name', models.CharField(max_length=200)),('indicative_date', models.DateField(blank=True, null=True)),('status', models.CharField(default='active', max_length=20)),('link_reorder_strategy', models.CharField(default='move_to_first', max_length=40)),('latest_server_sequence_number', models.PositiveIntegerField(default=0)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='JamTransaction', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('transaction_id', models.CharField(max_length=100, unique=True)),('client_id', models.CharField(max_length=100)),('client_sequence_number', models.PositiveIntegerField()),('schema_version', models.PositiveIntegerField(default=1)),('server_sequence_number_start', models.PositiveIntegerField()),('server_sequence_number_end', models.PositiveIntegerField()),('is_reverted', models.BooleanField(default=False)),('created_at', models.DateTimeField(auto_now_add=True)),('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='jams.jam'))], options={'ordering': ['server_sequence_number_start', 'id']}),
        migrations.CreateModel(name='JamClientSession', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('client_id', models.CharField(max_length=100)),('lease_token', models.CharField(max_length=120)),('is_active', models.BooleanField(default=True)),('lease_expires_at', models.DateTimeField()),('last_heartbeat_at', models.DateTimeField(auto_now=True)),('created_at', models.DateTimeField(auto_now_add=True)),('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to='jams.jam'))]),
        migrations.CreateModel(name='JamSnapshot', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('snapshot_id', models.CharField(max_length=100, unique=True)),('last_server_sequence_number', models.PositiveIntegerField()),('state', models.JSONField(default=dict)),('created_by_client_id', models.CharField(max_length=100)),('created_at', models.DateTimeField(auto_now_add=True)),('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='jams.jam'))], options={'ordering': ['-last_server_sequence_number', '-created_at']}),
        migrations.CreateModel(name='JamEvent', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('event_id', models.CharField(max_length=100, unique=True)),('type', models.CharField(max_length=80)),('payload', models.JSONField(default=dict)),('schema_version', models.PositiveIntegerField(default=1)),('server_sequence_number', models.PositiveIntegerField()),('created_at', models.DateTimeField(auto_now_add=True)),('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jams.jam')),('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jams.jamtransaction'))], options={'ordering': ['server_sequence_number', 'id']}),
        migrations.AddConstraint(model_name='jamtransaction', constraint=models.UniqueConstraint(fields=('jam','client_id','client_sequence_number'), name='unique_client_sequence_per_jam')),
        migrations.AddConstraint(model_name='jamclientsession', constraint=models.UniqueConstraint(fields=('jam','client_id'), name='unique_client_session_per_jam')),
    ]
