# Generated by Django 5.2.15 on 2026-06-13 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_legacy_round_data(apps, schema_editor):
    ParticipantEntry = apps.get_model("jams", "ParticipantEntry")
    Hole = apps.get_model("jams", "Hole")
    LinkGroup = apps.get_model("jams", "LinkGroup")
    PlayedPassage = apps.get_model("jams", "PlayedPassage")
    RoundSlot = apps.get_model("jams", "RoundSlot")
    SlotLinkGroup = apps.get_model("jams", "SlotLinkGroup")
    Plateau = apps.get_model("jams", "Plateau")

    entry_slot_ids = {}
    hole_slot_ids = {}

    for entry in ParticipantEntry.objects.select_related("jam", "instrument").order_by("id"):
        slot, _created = RoundSlot.objects.get_or_create(
            participant_entry_id=entry.id,
            round_number=1,
            defaults={
                "jam_id": entry.jam_id,
                "instrument_id": entry.instrument_id,
                "slot_type": "entry",
                "display_order": entry.base_order,
                "status": "planned",
            },
        )
        entry_slot_ids[entry.id] = slot.id

    for hole in Hole.objects.select_related("jam", "instrument").order_by("id"):
        slot = RoundSlot.objects.create(
            jam_id=hole.jam_id,
            instrument_id=hole.instrument_id,
            participant_entry_id=None,
            slot_type="hole",
            round_number=1,
            display_order=hole.position,
            status="planned",
            created_by_action=hole.created_by_action,
        )
        hole_slot_ids[hole.id] = slot.id

    for legacy_group in LinkGroup.objects.prefetch_related("entries", "holes").order_by("id"):
        slot_ids = [entry_slot_ids[entry.id] for entry in legacy_group.entries.all() if entry.id in entry_slot_ids]
        slot_ids += [hole_slot_ids[hole.id] for hole in legacy_group.holes.all() if hole.id in hole_slot_ids]
        if len(slot_ids) >= 2:
            group = SlotLinkGroup.objects.create(jam_id=legacy_group.jam_id, reason="manual", status="active")
            group.slots.set(slot_ids)

    plateau_groups = {}
    for passage in PlayedPassage.objects.order_by("jam_id", "line_index", "played_at", "id"):
        slot_id = None
        if passage.participant_entry_id:
            slot_id = entry_slot_ids.get(passage.participant_entry_id)
        elif passage.hole_id:
            slot_id = hole_slot_ids.get(passage.hole_id)
        if not slot_id:
            continue
        RoundSlot.objects.filter(id=slot_id).update(status="played", played_at=passage.played_at)
        key = (passage.jam_id, passage.line_index)
        plateau_groups.setdefault(key, {"played_at": passage.played_at, "slot_ids": []})
        # Stable rule: use the earliest played_at in the legacy line_index group.
        if passage.played_at < plateau_groups[key]["played_at"]:
            plateau_groups[key]["played_at"] = passage.played_at
        plateau_groups[key]["slot_ids"].append(slot_id)

    for (jam_id, _line_index), data in plateau_groups.items():
        plateau = Plateau.objects.create(jam_id=jam_id, status="played", played_at=data["played_at"])
        plateau.slots.set(data["slot_ids"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("jams", "0002_jam_editing_lock_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoundSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slot_type",
                    models.CharField(
                        choices=[("entry", "Entry"), ("hole", "Hole")],
                        default="entry",
                        max_length=16,
                    ),
                ),
                ("round_number", models.PositiveIntegerField(default=1)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("played", "Played"),
                            ("skipped", "Skipped"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("played_at", models.DateTimeField(blank=True, null=True)),
                ("created_by_action", models.CharField(blank=True, max_length=64)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_slots",
                        to="jams.instrument",
                    ),
                ),
                (
                    "jam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_slots",
                        to="jams.jam",
                    ),
                ),
                (
                    "participant_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_slots",
                        to="jams.participantentry",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "instrument__order",
                    "display_order",
                    "round_number",
                    "id",
                ],
            },
        ),
        migrations.CreateModel(
            name="Plateau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="played", max_length=16)),
                ("played_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "jam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plateaux",
                        to="jams.jam",
                    ),
                ),
                (
                    "slots",
                    models.ManyToManyField(
                        blank=True, related_name="plateaux", to="jams.roundslot"
                    ),
                ),
            ],
            options={
                "ordering": ["-played_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="SlotLinkGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("wants_to_play_together", "Wants to play together"),
                            ("wants_to_play_without", "Wants to play without"),
                        ],
                        default="manual",
                        max_length=40,
                    ),
                ),
                ("status", models.CharField(default="active", max_length=16)),
                (
                    "jam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_link_groups",
                        to="jams.jam",
                    ),
                ),
                (
                    "slots",
                    models.ManyToManyField(
                        blank=True, related_name="link_groups", to="jams.roundslot"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(migrate_legacy_round_data, noop_reverse),
        migrations.AddConstraint(
            model_name="roundslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("participant_entry__isnull", False)),
                fields=("participant_entry", "round_number"),
                name="unique_round_slot_per_entry_round",
            ),
        ),
        migrations.AddConstraint(
            model_name="roundslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("participant_entry__isnull", False), ("slot_type", "entry")
                    ),
                    models.Q(
                        ("participant_entry__isnull", True), ("slot_type", "hole")
                    ),
                    _connector="OR",
                ),
                name="round_slot_type_matches_entry_presence",
            ),
        ),
    ]
