EVENT_TYPES = {
    'jam_created',
    'jam_updated',
    'jam_link_reorder_strategy_changed',
    'instrument_added',
    'instrument_updated',
    'instruments_reordered',
    'instrument_visibility_changed',
    'instrument_round_visibility_changed',
    'participant_created',
    'participant_updated',
    'participant_removed',
    'participant_marked_left',
    'participation_added',
    'participation_removed',
    'appearance_materialized',
    'appearance_moved_between',
    'appearance_locked',
    'appearance_unlocked',
    'appearance_skipped',
    'appearance_removed',
    'hole_added',
    'hole_removed',
    'hole_moved_between',
    'hole_locked',
    'hole_unlocked',
    'link_created',
    'link_removed',
    'conflict_created',
    'conflict_removed',
    'plateau_played',
    'plateau_unplayed',
    'transaction_reverted',
}

NON_V0_EVENT_TYPES = {
    'jam_metadata_updated',
    'participant_left',
    'appearance_reordered',
    'appearance_deleted',
    'hole_reordered',
    'lock_added',
    'lock_removed',
    'play_without_created',
    'play_without_removed',
    'link_updated',
    'conflict_updated',
    'participation_updated',
    'appearance_note_updated',
    'participation_note_updated',
    'event_reverted',
    'plateau_composition_forced',
}


def is_allowed_event_type(event_type):
    return event_type in EVENT_TYPES
